# Generated by Django 4.2.11 on 2024-11-07 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hrms', '0002_leaverequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='notes',
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='remaining_days',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Declined', 'Declined')], max_length=20),
        ),
    ]
