# Generated by Django 4.2.11 on 2024-11-10 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hrms', '0004_remove_leaverequest_remaining_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='days_approved',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='days_requested',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('vacation', 'Vacation'), ('sick', 'Sick Leave'), ('personal', 'Personal Leave')], max_length=20),
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('attendance_status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('on_leave', 'On Leave')], max_length=20)),
                ('source', models.CharField(choices=[('biometric', 'Biometric'), ('web', 'Web Login')], max_length=50)),
                ('is_late', models.BooleanField(default=False)),
                ('late_duration', models.DurationField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
