# Generated by Django 4.2.11 on 2024-11-10 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0005_leaverequest_days_approved_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobPost',
        ),
    ]
