# Generated by Django 5.1.3 on 2024-11-17 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0010_alter_generatedreport_metrics_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedreport',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='generatedreport',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
