# Generated by Django 5.1.3 on 2024-11-17 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0012_alter_generatedreport_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedreport',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
