# Generated by Django 5.1.3 on 2024-11-17 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0013_alter_generatedreport_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedreport',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
