# Generated by Django 5.1.3 on 2024-11-24 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0016_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancerecord',
            name='source',
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='remarks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='attendance_status',
            field=models.CharField(blank=True, choices=[('present', 'Present'), ('absent', 'Absent'), ('on_leave', 'On Leave')], max_length=20, null=True),
        ),
    ]
