# Generated by Django 5.1.4 on 2025-01-01 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0018_remove_attendancerecord_attendance_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancerecord',
            name='remarks',
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(default='no info', max_length=20),
        ),
    ]
