# Generated by Django 5.1.4 on 2025-01-01 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0019_remove_attendancerecord_remarks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='checkout_status',
            field=models.CharField(default='no info', max_length=20),
        ),
    ]
