# Generated by Django 5.1.3 on 2024-11-17 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_customuser_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='work_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='work_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
