# Generated by Django 5.1.3 on 2024-11-24 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_department_work_end_time_department_work_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='work_end_time',
        ),
        migrations.AddField(
            model_name='department',
            name='late_checkin_buffer',
            field=models.IntegerField(default=10),
        ),
    ]
