# Generated by Django 5.1.4 on 2024-12-27 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_department_work_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='work_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
