# Generated by Django 5.1.4 on 2025-02-23 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_department_work_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='otp_secret',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
